/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/irgjnThXFF3
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages xDirectory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

"use client";

import { Input } from "@/components/ui/input"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { useState } from 'react'
import { useEffect } from 'react'
import { Button } from "./ui/button";
import Link from 'next/link';

export function CaseList({ session }: { session: any }) {
  const [cases, setCases] = useState([]);

  useEffect(() => {
    fetch('/api/cases')
      .then(response => response.json())
      .then(data => {
        console.log(data); // Print out the response here
        setCases(data);
      })
      .catch(error => console.error(error));
  }, [session]);


  const handleDelete = async (id: string) => {
    try {
      const response = await fetch(`/api/cases`, {
        method: 'DELETE',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ id }),
      });
  
      if (!response.ok) {
        throw new Error('Network response was not ok');
      }
  
      const data = await response.json();
      console.log(data);
      setCases(cases.filter((item: { _id: string }) => item._id !== id));
    } catch (error) {
      console.error('Error deleting data:', error);
    }
  }

  return (
    <div className="bg-[#FCFCF7] dark:bg-gray-950 rounded-lg shadow-md p-6" style={{ height: 'calc(100vh - 8rem)' }}>
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-2xl font-bold text-[#082940]">Case List</h2>
        <div className="relative">
          <SearchIcon className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-500 dark:text-gray-400 w-5 h-5" />
          <Input
            className="pl-10 pr-4 py-2 rounded-md border border-gray-20 dark:border-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 dark:focus:ring-blue-400 dark:focus:border-blue-400 w-64"
            placeholder="Search cases..."
            type="text"
          />
        </div>
      </div>
      <div className="max-h-[400px] overflow-y-auto">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="">Created</TableHead>
              <TableHead>First</TableHead>
              <TableHead>Last</TableHead>
              <TableHead>Client ID</TableHead>
              <TableHead>Letter Type</TableHead>
              <TableHead>Action</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {cases.map((item: any, index: number) => (
              <TableRow key={index}>
                {/* Add table cells here */}
                <TableCell>{new Date(item.createdDate).toLocaleString('en-US', { month: 'numeric', day: 'numeric', year: '2-digit', hour: 'numeric', minute: 'numeric' })}</TableCell>
                <TableCell>{item.first}</TableCell>
                <TableCell>{item.last}</TableCell>
                <TableCell>{item._id}</TableCell>
                <TableCell>{item.letterType}</TableCell>
                <TableCell>  
                  <Link href={`/editor?id=${btoa(item._id)}`}>
                    <Button className="bg-white text-black hover:bg-gray-200 border-2">View</Button>
                  </Link>
                  <Link href={`/files?id=${btoa(item._id)}`}>
                    <Button className="bg-white ml-5 text-black hover:bg-gray-200 border-2">Files</Button>
                  </Link>
                  <Button onClick={() => handleDelete(item._id)} className="ml-5 bg-red-500 hover:bg-red-300">Delete</Button>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </div>
  )
}

function SearchIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
