/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9BXBtumzNnU
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"

export function ClientList() {
  return (
    <section className="w-full max-w-4xl mx-auto py-12 px-4 md:px-6" style={{ height: 'calc(100vh - 8rem)' }}>
      <div className="space-y-6">
        <div className="text-center">
          <h1 className="text-3xl font-bold">Select a Client</h1>
          <p className="text-gray-500 dark:text-gray-400">Choose from our list of clients to get started.</p>
        </div>
        <div className="relative">
          <SearchIcon className="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-500 dark:text-gray-400" />
          <Input className="pl-12 w-full" placeholder="Search clients..." type="search" />
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          <div className="bg-white rounded-lg overflow-hidden shadow-lg dark:bg-gray-950">
            <div className="p-4 space-y-2">
              <h3 className="text-lg font-semibold">John Doe</h3>
              <p className="text-gray-500 dark:text-gray-400 line-clamp-2">
                John is a seasoned entrepreneur with a passion for innovative solutions. He has a proven track record of
                building successful startups.
              </p>
            </div>
          </div>
          <div className="bg-white rounded-lg overflow-hidden shadow-lg dark:bg-gray-950">
            <div className="p-4 space-y-2">
              <h3 className="text-lg font-semibold">Jane Smith</h3>
              <p className="text-gray-500 dark:text-gray-400 line-clamp-2">
                Jane is a marketing expert with a keen eye for trends and consumer insights. She has helped numerous
                businesses achieve remarkable growth.
              </p>
            </div>
          </div>
          <div className="bg-white rounded-lg overflow-hidden shadow-lg dark:bg-gray-950">
            <div className="p-4 space-y-2">
              <h3 className="text-lg font-semibold">Michael Johnson</h3>
              <p className="text-gray-500 dark:text-gray-400 line-clamp-2">
                Michael is a talented designer with a passion for creating visually stunning and user-friendly
                interfaces. He has worked with a variety of clients across different industries.
              </p>
            </div>
          </div>
          <div className="bg-white rounded-lg overflow-hidden shadow-lg dark:bg-gray-950">
            <div className="p-4 space-y-2">
              <h3 className="text-lg font-semibold">Emily Davis</h3>
              <p className="text-gray-500 dark:text-gray-400 line-clamp-2">
                Emily is a strategic thinker with a strong background in business development. She has helped numerous
                startups and established companies achieve their growth goals.
              </p>
            </div>
          </div>
          <div className="bg-white rounded-lg overflow-hidden shadow-lg dark:bg-gray-950">
            <div className="p-4 space-y-2">
              <h3 className="text-lg font-semibold">David Lee</h3>
              <p className="text-gray-500 dark:text-gray-400 line-clamp-2">
                David is a software engineer with a passion for building scalable and efficient systems. He has worked
                on a variety of projects, from mobile apps to enterprise-level applications.
              </p>
            </div>
          </div>
          <div className="bg-white rounded-lg overflow-hidden shadow-lg dark:bg-gray-950">
            <div className="p-4 space-y-2">
              <h3 className="text-lg font-semibold">Sarah Wilson</h3>
              <p className="text-gray-500 dark:text-gray-400 line-clamp-2">
                Sarah is a digital marketing expert with a proven track record of driving successful campaigns. She has
                helped numerous businesses increase their online visibility and reach.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

function SearchIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
