'use client';

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/2p4Yk4AvmwX
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { Button } from "@/components/ui/button"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { Progress } from "@/components/ui/progress"
import { useRef, useState, useEffect } from 'react';
import { useSearchParams } from 'next/navigation'
import { FileEdit } from "lucide-react";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faCircleNotch } from '@fortawesome/free-solid-svg-icons';

type FileWithCategory = File & { category?: string, _id: string, indexed: boolean};

export function FileManager({ session }: { session: any }) {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [files, setFiles] = useState<Array<{ name: string, id: string, progress: number, uploaded: boolean, indexed: boolean, size: number, category?: string }>>([]);
  const searchParams = useSearchParams();
  const id = searchParams.get('id');
  const cid = atob(id as string);
  const [processing, setProcessing] = useState<{ [key: string]: boolean }>({});
  const [refreshFilesKey, setRefreshFilesKey] = useState(0);

  const handleUploadClick = (event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => {
    event.preventDefault();
    if (fileInputRef.current) {
      fileInputRef.current.click();
    }
  };

  useEffect(() => {
    fetch(`/api/files?cid=${cid}`)
      .then(response => {
        if (!response.ok) {
          throw new Error('Network response was not ok');
        }
        return response.json();
      })
      .then(data => {
        console.log(data);
  
        const files = data.map((file: FileWithCategory) => ({
          name: file.name,
          id: file._id,
          progress: 100,
          uploaded: true,
          indexed: file.indexed,
          size: file.size,
          category: file.category,
        }));
  
        setFiles(files);
      })
      .catch(error => {
        console.error(error);
      });
  }, [refreshFilesKey, cid]);

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (event.target.files) {
      for (let i = 0; i < event.target.files.length; i++) {
        const file = event.target.files[i] as FileWithCategory;
        uploadFile(file);
      }
    }
  };

  const uploadFile = (file: FileWithCategory) => {
    // First, get the signed URL from the server
    fetch('/api/getSignedUrl', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        fileName: file.name,
        fileType: file.type,
      }),
    })
      .then(response => {
        if (!response.ok) {
          throw new Error('Network response was not ok');
        }
        return response.json();
      })
      .then(data => {
        // Then, use the signed URL to upload the file
        const signedUrl = data.signedUrl;
        return fetch(signedUrl, {
          method: 'PUT',
          body: file,
          headers: {
            'Content-Type': file.type, // Set the correct content type for the upload
          },
        });
      })
      .then(response => {
        if (!response.ok) {
          throw new Error('Network response was not ok');
        }
        // File upload was successful
        const newFile = {
          name: file.name,
          progress: 100,
          uploaded: true,
          indexed: false,
          size: file.size,
          id: file.name, // Assuming the file name is used as the ID
          category: file.category, // Ensure category is included
        };
        setFiles(prevFiles => [...prevFiles, newFile]);
      })
      .catch(error => {
        console.error('Error:', error);
      });
  };

  const deleteFile = (fileId: string) => {
    const file = files.find(f => f.id === fileId);
  
    if (file) {
      setFiles(prevFiles => prevFiles.filter(f => f.id !== fileId));
  
      fetch('/api/files', {
        method: 'DELETE',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ id: fileId }),
      })
        .then(response => {
          if (!response.ok) {
            throw new Error('Network response was not ok');
          }
          return response.json();
        })
        .then(data => {
          console.log(data);
        })
        .catch(error => {
          console.error(error);
        });
    } else {
      console.error('File is either not found or still indexed');
    }
  };
  
  type BadgeProps = {
    children: React.ReactNode;
    color: string;
  };
  
  const Badge = ({ children, color }: BadgeProps) => (
    <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${color}`}>
      {children}
    </span>
  );

  const processFile = async (id: string) => {
    try {
      setProcessing(prevState => ({ ...prevState, [id]: true }));
      // Get the current state of the file
      const file = files.find(f => f.id === id);
  
      if (!file) {
        throw new Error('File not found');
      }
  
      if (file.indexed) {
        // If the file is already indexed, unindex it
        const response = await fetch('/api/unindex', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({ id }),
        });
  
        if (!response.ok) {
          throw new Error('Error unindexing file');
        }
  
        const data = await response.json();
        console.log(data);
        setFiles(prevFiles => prevFiles.map(f => f.id === id ? { ...f, indexed: false } : f));
        setProcessing(prevState => ({ ...prevState, [id]: false }));
      } else {
        const response = await fetch('/api/process', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({ id, clientId: cid }),
        });
  
        if (!response.ok) {
          throw new Error('Error processing file');
        }
  
        const data = await response.json();
        console.log(data);
  
        const taskId = data.taskId;
  
        if (taskId) {
          // Start polling for task status
          const intervalId = setInterval(() => {
            fetch(`/api/process-status?taskId=${taskId}`)
              .then(response => response.json())
              .then(data => {
                console.log('Task status:', data.status);
                //refresh file list
  
                //setProcessingStatus(data.status);
                //setProgress(data.percentComplete);
  
                // If the task is complete, stop polling
                if (data.status === 'completed') {
                  clearInterval(intervalId);
                  // Redirect to the results page
                  setFiles(prevFiles => prevFiles.map(f => f.id === id ? { ...f, indexed: true } : f));
                  setProcessing(prevState => ({ ...prevState, [id]: false }));
                  setRefreshFilesKey(prevKey => prevKey + 1);
                }
              });
          }, 3000); // Adjust the polling interval as needed
        }
      }
    } catch (error) {
      console.error(error);
      setProcessing(prevState => ({ ...prevState, [id]: false }));
    }
  };
  
  return (
    <div className="container mx-auto px-4 py-8">
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold">File Manager</h1>
        <Button size="sm" onClick={handleUploadClick}>
          <UploadIcon className="mr-2 h-4 w-4" />
          Upload new file
        </Button>
        <input type="file" ref={fileInputRef} onChange={handleFileChange} style={{ display: 'none' }} multiple />
      </div>
      <div className="hover:bg-[#fcfaf7] dark:bg-gray-900 rounded-lg shadow-md overflow-hidden">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="w-[30%]">File</TableHead>
              <TableHead className="w-[10%]">Size</TableHead>
              <TableHead className="w-[20%]">Category</TableHead>
              <TableHead className="w-[20%]">Progress</TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
        </Table>
        <div style={{ maxHeight: '700px', overflow: 'auto' }}>
          <Table>
            <TableBody>
              {files.map((f, index) => (
                <TableRow key={index}>
                  <TableCell className="w-[30%]"><i>{f.name}</i></TableCell>
                  <TableCell className="w-[10%]">{(f.size / 1024 / 1024).toFixed(2)} MB</TableCell>
                  <TableCell className="w-[20%]"><b>{f.category}</b></TableCell>
                  <TableCell className="w-[20%]">
                    <div className="flex gap-1 justify-between items-center">
                      <Progress className="text-gray-600" value={f.progress} />
                      <div className="flex gap-1">
                        <Badge color={f.uploaded ? 'bg-blue-200 text-blue-800' : 'bg-gray-200 text-gray-800'}>U</Badge>
                        <button onClick={() => processFile(f.id)} disabled={processing[f.id]}>
                          <Badge color={f.indexed ? 'bg-blue-200 text-green-800' : 'bg-gray-200 text-gray-800'}>
                            <div className="w-2 h-6 flex items-center justify-center">
                              {processing[f.id] ? (
                                <FontAwesomeIcon icon={faCircleNotch} className="animate-spin" />
                              ) : (
                                'I'
                              )}
                            </div>
                          </Badge>
                        </button>
                      </div>
                    </div>
                  </TableCell>
                  <TableCell className="text-right">
                    <Button onClick={() => deleteFile(f.id)}>Delete</Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      </div>
    </div>
  );
}

function DownloadIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" x2="12" y1="15" y2="3" />
    </svg>
  )
}

function FileIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
    </svg>
  )
}

function TrashIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>
  )
}

function UploadIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>
  )
}
