/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/AhAGvUb2Da9
 */


export function Footer() {
  return (
    <footer className="bg-[#1f1f1f] p-4 h-16 text-white text-left">
      <p>© Pravina 2024</p>
    </footer>
  )
}
