/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Ev7Sy3VOEoy
 */
import Link from "next/link"

export function Header() {
  return (
    <header className="flex items-center h-16 justify-between bg-white px-4 py-4 w-full">
      <div className="flex items-center space-x-0">
        <GavelIcon className="h-6 w-6 text-black" />
        <Link href="/">
        <span className="text-xl font-bold text-black pl-3">Pravina</span>
        </Link>
      </div>
    </header>
  )
}


function GavelIcon(props: any) {
  return (
      <svg
          {...props}
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
      >
          <path d="m14 13-7.5 7.5c-.83.83-2.17.83-3 0 0 0 0 0 0 0a2.12 2.12 0 0 1 0-3L11 10" />
          <path d="m16 16 6-6" />
          <path d="m8 8 6-6" />
          <path d="m9 7 8 8" />
          <path d="m21 11-8-8" />
      </svg>
  )
}