/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/cM1nrZxeqYp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Chivo } from 'next/font/google'

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function HomeComponent() {
  return (
    <section className="flex flex-col justify-center bg-[#FCFCF7] px-6" style={{ height: 'calc(100vh - 8rem)' }}>
      <div className="max-w-3xl mx-auto text-center">
        <h1 className="h1-custom text-5xl text-[#082940]">Welcome to Pravina</h1>
        <p className="mt-6 p-custom text-lg">Welcome to our MVP. In the next few steps, you’ll be able to upload your client information and generate an EB1 support letter.</p>
        <div className="mt-8 flex justify-center gap-4">
          <Button className="bg-[#7D6430] hover:bg-[#bda97f]">
            <Link
              className="inline-flex items-center justify-center px-5 py-2 text-white font-medium rounded-md shadow-sm"
              href="/new"
              style={{
                borderRadius: '8px',
              }}
            >
              Lets get started
            </Link>
          </Button>
          <Button className="bg-[#7D6430] hover:bg-[#bda97f]">
          <Link
            className="inline-flex items-center justify-center px-5 py-2 text-white font-medium rounded-md shadow-sm"
            href="/cases"
            style={{
              borderRadius: '8px',
            }}
          >
            Existing Case
          </Link>
          </Button>
        </div>
      </div>
    </section>
  )
}