/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/MTh2iTTR6qA
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

/** Add border radius CSS variable to your global CSS:

:root {
  --radius: 0.5rem;
}
**/
import { CardTitle, CardDescription, CardHeader, Card, CardContent, CardFooter } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"
import { OverallProgress } from "@/components/overall-progress";
import Link from 'next/link';
import { Button } from "@/components/ui/button";

export function Instructions() {
  return (
    <div className="pt-8" style={{ height: 'calc(100vh - 8rem)' }}>
      <Card className="w-full max-w-2xl" >
        <CardHeader className="items-center">
          <CardTitle>Get Started</CardTitle>
          <CardDescription>Follow these step-by-step instructions to get started with our product.</CardDescription>
        </CardHeader>
        <CardContent className="grid gap-4">
          <div className="grid gap-4">
            <Card className="p-4">
              <div className="flex items-start gap-2">
                <DocumentAddIcon className="mt-1 h-5 w-5 text-gray-900 dark:text-gray-50" />
                <div>
                  <h4 className="font-semibold">Choose Letter Type</h4>
                  <p className="text-gray-600">Select the type of letter you want to generate.</p>
                </div>
              </div>
            </Card>
            <Card className="p-4">
              <div className="flex items-start gap-2">
                <CloudUploadIcon className="mt-1 h-5 w-5 text-gray-900 dark:text-gray-50" />
                <div>
                  <h4 className="font-semibold">Upload Supporting Documentation</h4>
                  <p>Upload your supporting documents in a .zip file format.</p>
                </div>
              </div>
            </Card>
            <Card className="p-4">
              <div className="flex items-start gap-2">
                <RefreshIcon className="mt-1 h-5 w-5 text-gray-900 dark:text-gray-50" />
                <div>
                  <h4 className="font-semibold">Wait for Indexing to Complete</h4>
                  <p>Wait for the system to complete indexing your uploaded documents.</p>
                </div>
              </div>
            </Card>
            <Card className="p-4">
              <div className="flex items-start gap-2">
                <DocumentTextIcon className="mt-1 h-5 w-5 text-gray-900 dark:text-gray-50" />
                <div>
                  <h4 className="font-semibold">Generate Letter</h4>
                  <p>Generate your letter based on the uploaded documents and chosen letter type.</p>
                </div>
              </div>
            </Card>
            <Card className="p-4">
              <div className="flex items-start gap-2">
                <DownloadIcon className="mt-1 h-5 w-5 text-gray-900 dark:text-gray-50" />
                <div>
                  <h4 className="font-semibold">Download Letter</h4>
                  <p>Download your generated letter in a preferred format.</p>
                </div>
              </div>
            </Card>
          </div>
        </CardContent>
        <CardFooter>
          <OverallProgress />
          <Link href="/upload">
            <Button className="">Next</Button>
          </Link>
        </CardFooter>
      </Card>
    </div>
  )
}
function DocumentAddIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
    </svg>
  )
}

function CloudUploadIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 16s-1.5-2.5-4-2.5-4 2.5-4 2.5" />
      <path d="M12 12v4" />
      <path d="M12 12l-3-3" />
      <path d="M12 12l3-3" />
    </svg>
  )
}

function RefreshIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 20v-2a4 4 0 00-4-4H4" />
      <path d="M4 4v2a4 4 0 004 4h12" />
    </svg>
  )
}

function DocumentTextIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 6h16M4 10h16M4 14h16M4 18h16" />
    </svg>
  )
}

function DownloadIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 4v2a4 4 0 004 4h12" />
      <path d="M12 14l-4 4m8 0l-4-4m4 4v-6" />
    </svg>
  )
}