'use client';


/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/HVjRIxZVrRc
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { signIn } from 'next-auth/react'
import { useState } from 'react';
import { PassThrough } from "stream";
import { useSession} from "next-auth/react";
import { useRouter } from "next/navigation";

export function Login() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const { data: session } = useSession();
  const router = useRouter();

  if (session) {
    router.push('/home');
  }

  const handleSubmit = (e:any) => {
    e.preventDefault();
    signIn('credentials', {username, password, callbackUrl: '/home'});
  };

  return (
    <main className="flex flex-col items-center justify-center bg-[#FCFCF7] dark:bg-gray-900" style={{ height: 'calc(100vh - 8rem)' }}>
      <div className="mx-auto flex w-full max-w-md flex-col space-y-6 rounded-lg bg-white p-6 shadow-lg dark:bg-gray-800 sm:p-8">
        <div className="space-y-2 text-center">
          <h1 className="text-3xl font-bold text-[#082940]">Login</h1>
          <p className="text-gray-500 dark:text-gray-400">Enter your credentials to access your account.</p>
        </div>
        <form className="space-y-6" onSubmit={handleSubmit}>
          <div>
            <Label className="text-left font-medium text-[#082940]" htmlFor="username">
              Username
            </Label>
            <Input className="w-full" id="username" placeholder="your@email.com" required type="text" value={username} onChange={(e) => setUsername(e.target.value)} />
          </div>
          <div>
            <Label className="text-left font-medium text-[#082940]" htmlFor="password">
              Password
            </Label>
            <Input className="w-full" id="password" placeholder="••••••••" required type="password" value={password} onChange={(e) => setPassword(e.target.value)}/>
          </div>
          <Button className="w-full" type="submit" >
            Login
          </Button>
        </form>
        <div className="text-center">
          <Link
            className="text-sm text-gray-500 underline underline-offset-4 hover:text-gray-600 dark:text-gray-400 dark:hover:text-gray-300"
            href="#"
          >
            Forgot your password?
          </Link>
        </div>
        <div className="text-center">
          <Link
            className="text-sm text-gray-500 underline underline-offset-4 hover:text-gray-600 dark:text-gray-400 dark:hover:text-gray-300"
            href="/signup"
          >
            Sign Up
          </Link>
        </div>
      </div>
    </main>
  )
}
