/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/KsITTrPwads
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
export function OverallProgress() {
  return (
    <div className="flex items-center justify-center py-8">
      <div className="flex items-center">
        <div className="relative flex items-center justify-center w-10 h-10 bg-white border-2 border-[#D9D9D9] rounded-full">
          <CheckIcon className="text-[#6B7280]" />
          <span className="text-xs font-medium text-[#6B7280]">Client Information</span>
        </div>
        <div className="w-24 h-1 bg-[#D9D9D9]" />
        <div className="flex items-center justify-center w-10 h-10 bg-white border-2 border-[#D9D9D9] rounded-full">
          <CheckIcon className="text-[#6B7280]" />
          <span className="text-xs font-medium text-[#6B7280] mt-14">Visa Type</span>
        </div>
        <div className="w-24 h-1 bg-[#D9D9D9]" />
        <div className="flex items-center justify-center w-10 h-10 bg-[#6B7280] border-2 border-[#D9D9D9] rounded-full">
          <CheckIcon className="text-white" />
          <span className="text-xs font-medium text-[#6B7280]  mt-14">Eligibility Evidence (1/10)</span>
        </div>
        <div className="w-24 h-1 bg-[#D9D9D9]" />
        <div className="flex items-center justify-center w-10 h-10 bg-white border-2 border-[#D9D9D9] rounded-full">
          <XIcon className="text-[#6B7280]" />
        </div>
      </div>
    </div>
  )
}

function CheckIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function XIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
