/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/g87oBiIIQ3r
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client';

import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"
import { useEffect } from 'react';
import { useState } from 'react';

export function ProcessingComponent({session}: {session: any}) {
  const [processingStatus, setProcessingStatus] = useState('Processing...');
  const [progress, setProgress] = useState(2);


  console.log(session);
  useEffect(() => {
      // Grab id from URL param
      const urlParams = new URLSearchParams(window.location.search);
      const id = urlParams.get('id');

      // Convert id back from base64
      if (id) {
        const cid = atob(id as string);
              // Call the process API with id as param in body
        fetch('/api/process', {
          method: 'POST',
          body: JSON.stringify({ id: cid }),
          headers: {
            'Content-Type': 'application/json'
          }
        })
          .then(response => response.json())
          .then(data => {
            // Assume the server returns a task ID
            const taskId = data.taskId;
        
            if (taskId) {

            // Start polling for task status
            const intervalId = setInterval(() => {
              fetch(`/api/process-status?taskId=${taskId}`)
                .then(response => response.json())
                .then(data => {
                  console.log('Task status:', data.status);
                  setProcessingStatus(data.status);
                  setProgress(data.percentComplete);
        
                  // If the task is complete, stop polling
                  if (data.status === 'completed') {
                    clearInterval(intervalId);
                    // Redirect to the results page
                    //window.location.href = `/results?id=${btoa(cid)}`;
                    window.location.href = `/editor?id=${btoa(cid)}`;
                  }
                })
                .catch(error => console.error(error));
            }, 5000);
            }  // Poll every 5 seconds
          })
          .catch(error => console.error(error));
      }
    }, []);
  
  return (
    <Card className="w-full max-w-md">
      <CardHeader>
        <CardTitle>Processing Data</CardTitle>
        <CardDescription>
          We are currently processing and analyzing your data. This may take a few minutes.
        </CardDescription>
      </CardHeader>
      <CardContent className="flex flex-col items-start gap-4">
        <Progress className="w-full" value={progress}>
          <div className="flex items-center justify-between">
            <span>75%</span>
            <span>Processing...</span>
          </div>
        </Progress>
      </CardContent>
    </Card>
  )
}
