'use client';

/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/EtRWICabzAL
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { useState } from 'react';
import { set } from "mongoose";
import { useRouter } from 'next/navigation';

export function SignUp() {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [successMessage, setSuccessMessage] = useState(false);
  const [errorMessage, setErrorMessage] = useState(false);
  const Router = useRouter();

  const handleSignUp = (event: React.FormEvent) => {
    event.preventDefault();

    console.log('Name:', name);
    console.log('Email:', email);
    // TODO: Call register API with the form data
    // Example:
    fetch('/api/register', {
      method: 'POST',
      body: JSON.stringify({
        name,
        email,
        password,
      }),
      headers: {
        'Content-Type': 'application/json',
      },
    })
      .then((response) => response.json())
      .then((data) => {
        // Handle the response from the API
        setSuccessMessage(true);
        Router.push('/');
      })
      .catch((error) => {
        // Handle any errors
        setErrorMessage(true);
      });
  };

  return (
    <section className="container mx-auto flex min-h-screen flex-col items-center justify-center px-4">
      <div className="mx-auto w-full max-w-md rounded-lg bg-white p-8 shadow-lg dark:bg-gray-800">
        <div className="mb-6 text-center">
          <h2 className="text-3xl font-bold">Create an Account</h2>
          <p className="mt-2 text-gray-500 dark:text-gray-400">Register to join Pravina today!</p>
        </div>
        <form className="space-y-4" onSubmit={handleSignUp}>
          <div>
            <Label className="mb-2 block font-medium" htmlFor="name">
              Name
            </Label>
            <Input
              id="name"
              placeholder="Enter your name"
              required
              type="text"
              value={name}
              onChange={(event) => setName(event.target.value)}
            />
          </div>
          <div>
            <Label className="mb-2 block font-medium" htmlFor="email">
              Email
            </Label>
            <Input
              id="email"
              placeholder="Enter your email"
              required
              type="email"
              value={email}
              onChange={(event) => setEmail(event.target.value)}
            />
          </div>
          <div>
            <Label className="mb-2 block font-medium" htmlFor="password">
              Password
            </Label>
            <Input
              id="password"
              placeholder="Enter your password"
              required
              type="password"
              value={password}
              onChange={(event) => setPassword(event.target.value)}
            />
          </div>
          <div>
            <Label className="mb-2 block font-medium" htmlFor="confirmPassword">
              Confirm Password
            </Label>
            <Input
              id="confirmPassword"
              placeholder="Confirm your password"
              required
              type="password"
              value={confirmPassword}
              onChange={(event) => setConfirmPassword(event.target.value)}
            />
          </div>
          <Button className="w-full" type="submit">
            Sign Up
          </Button>
        </form>
        <div className="mt-4 text-center">
          {successMessage && (
            <p className="mt-4 text-sm text-black">Registration successful!</p>
          )}
          {errorMessage && (
            <p className="mt-4 text-sm text-red-800">Registration failed. Please try again.</p>
          )}
        </div>
      </div>
    </section>
  );
}
